SET client_encoding = 'UTF8';
insert into answer(id, text, question_id, order_in_question) values (1, 'Jean-Luc', 2, 0);
insert into answer(id, text, question_id, order_in_question) values (2, 'Matthias', 2, 1);
insert into answer(id, text, question_id, order_in_question) values (3, 'Clementine', 2, 2);
insert into answer(id, text, question_id, order_in_question) values (4, 'Marie', 2, 3);
insert into answer(id, text, question_id, order_in_question) values (5, 'Ludo', 2, 4);
insert into answer(id, text, question_id, order_in_question) values (6, '20k - 25k brut/an', 5, 0);
insert into answer(id, text, question_id, order_in_question) values (7, '25k - 30k brut/an', 5, 1);
insert into answer(id, text, question_id, order_in_question) values (8, '30k - 35k brut/an', 5, 2);
insert into answer(id, text, question_id, order_in_question) values (9, '35k - 40k brut/an', 5, 3);
insert into answer(id, text, question_id, order_in_question) values (10, '45k - 50k brut/an', 5, 4);
insert into answer(id, text, question_id, order_in_question) values (11, '+ 50k brut/an', 5, 5);
Select setval('answer_id_seq', max(id)) from answer;