SET client_encoding = 'UTF8';
insert into question (id, text, answer_type, order_in_survey, survey_id) values (1, 'Comment vous appelez-vous ?', 'FREE', 0, 1);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (2, 'Quels professeurs avez-vous eu ?', 'CHOOSE_MANY', 1, 1);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (3, 'Etes-vous satisfait de votre formation ?', 'YES_NO', 2, 1);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (4, 'Etes-vous toujours dans votre entreprise ?', 'YES_NO', 0, 2);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (5, 'Sur quelle fourchette de salaire vous situez-vous ?', 'CHOOSE_ONE', 3, 1);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (6, 'Avez-vous trouvé un emploi suite a votre formation ?', 'YES_NO', 0, 3);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (7, 'Avez-vous garde contact avec les autres eleves de votre formation ?', 'YES_NO', 1, 2);
insert into question (id, text, answer_type, order_in_survey, survey_id) values (8, 'Avez-vous une remarque a faire pour nous aider a vous accompagner dans l''apres formation ?', 'FREE', 2, 2);
Select setval('question_id_seq', max(id)) from question;