SET client_encoding = 'UTF8';
insert into question (id, text, answer_type) values (1, 'Comment vous appelez-vous ?', 'FREE');
insert into question (id, text, answer_type) values (2, 'Quels professeurs avez-vous eu ?', 'CHOOSE_MANY');
insert into question (id, text, answer_type) values (3, 'Êtes-vous satisfait de votre formation ?', 'YES_NO');
insert into question (id, text, answer_type) values (4, 'Êtes-vous toujours dans votre entreprise ?', 'YES_NO');
insert into question (id, text, answer_type) values (5, 'Sur quelle fourchette de salaire vous situez-vous ?', 'CHOOSE_ONE');
insert into question (id, text, answer_type) values (6, 'Avez-vous trouvé un emploi suite à votre formation ?', 'YES_NO');
insert into question (id, text, answer_type) values (7, 'Avez-vous gardé contact avec les autres élèves de votre formation ?', 'YES_NO');
insert into question (id, text, answer_type) values (8, 'Avez-vous une remarque à faire pour nous aider à vous accompagner dans l''après formation ?', 'FREE');
Select setval('question_id_seq', max(id)) from question;